removes deprecated sample project
when trying to run the project, I get the following error:
```
Traceback (most recent call last):
File "manage.py", line 2, in <module>
from django.core.management import execute_manager
ImportError: cannot import name 'execute_manager'
```

It seems, the project folder was made with an old version of django,
since `execute_manager` is long deprecated.

Source:
https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-1-6